title:        linebreaks4imagettftext
name:         linebreaks4imagettftext
description:  linebreaks4imagettftext is a function to automatically insert line breaks into your text while using PHP's imagettftext function.
author:       Andrew G. Johnson
author_email: andrew@andrewgjohnson.com
email:        andrew@andrewgjohnson.com
url:          "https://linebreaks4imagettftext.agjgd.org"
includes_dir: .
layouts_dir:  documentation/linebreaks4imagettftext.agjgd.org/layouts
exclude:      [
               .github,
               .github/*.md,
               .github/*.yml,
               .github/CODEOWNERS,
               .github/ISSUE_TEMPLATE,
               .github/ISSUE_TEMPLATE/*.yml,
               CHANGELOG.md,
               CNAME,
               composer.json,
               documentation/README.md,
               examples/*.php,
               examples/*.ttf,
               examples/*.txt,
               LICENSE,
               README.md,
               source
              ]
